// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"
)

const deleteAuth = `-- name: DeleteAuth :exec
DELETE FROM auth WHERE twitch_bot_account_id = $1
`

func (q *Queries) DeleteAuth(ctx context.Context, twitchBotAccountID string) error {
	_, err := q.db.ExecContext(ctx, deleteAuth, twitchBotAccountID)
	return err
}

const getAuth = `-- name: GetAuth :one
SELECT twitch_bot_account_id, twitch_client_id, twitch_client_secret, oauth_key, oath_refresh_key FROM auth WHERE twitch_bot_account_id = $1
`

func (q *Queries) GetAuth(ctx context.Context, twitchBotAccountID string) (Auth, error) {
	row := q.db.QueryRowContext(ctx, getAuth, twitchBotAccountID)
	var i Auth
	err := row.Scan(
		&i.TwitchBotAccountID,
		&i.TwitchClientID,
		&i.TwitchClientSecret,
		&i.OauthKey,
		&i.OathRefreshKey,
	)
	return i, err
}

const refreshOath = `-- name: RefreshOath :exec
UPDATE auth 
SET oauth_key = $1, oath_refresh_key = $2
WHERE twitch_bot_account_id = $3
`

type RefreshOathParams struct {
	OauthKey           string
	OathRefreshKey     string
	TwitchBotAccountID string
}

func (q *Queries) RefreshOath(ctx context.Context, arg RefreshOathParams) error {
	_, err := q.db.ExecContext(ctx, refreshOath, arg.OauthKey, arg.OathRefreshKey, arg.TwitchBotAccountID)
	return err
}

const setAuth = `-- name: SetAuth :exec
INSERT INTO auth (
    twitch_bot_account_id,
    twitch_client_id,
    twitch_client_secret,
    oauth_key,
    oath_refresh_key
    ) 
VALUES ($1, $2, $3, $4, $5)
`

type SetAuthParams struct {
	TwitchBotAccountID string
	TwitchClientID     string
	TwitchClientSecret string
	OauthKey           string
	OathRefreshKey     string
}

func (q *Queries) SetAuth(ctx context.Context, arg SetAuthParams) error {
	_, err := q.db.ExecContext(ctx, setAuth,
		arg.TwitchBotAccountID,
		arg.TwitchClientID,
		arg.TwitchClientSecret,
		arg.OauthKey,
		arg.OathRefreshKey,
	)
	return err
}

const updateAuth = `-- name: UpdateAuth :exec
UPDATE auth 
SET twitch_client_id = $1, twitch_client_secret = $2, oauth_key = $3, oath_refresh_key = $4
WHERE twitch_bot_account_id = $5
`

type UpdateAuthParams struct {
	TwitchClientID     string
	TwitchClientSecret string
	OauthKey           string
	OathRefreshKey     string
	TwitchBotAccountID string
}

func (q *Queries) UpdateAuth(ctx context.Context, arg UpdateAuthParams) error {
	_, err := q.db.ExecContext(ctx, updateAuth,
		arg.TwitchClientID,
		arg.TwitchClientSecret,
		arg.OauthKey,
		arg.OathRefreshKey,
		arg.TwitchBotAccountID,
	)
	return err
}
