// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gc.sql

package database

import (
	"context"
	"database/sql"
)

const clearCurrentPlayback = `-- name: ClearCurrentPlayback :exec
DELETE FROM current_playback WHERE id = 1
`

func (q *Queries) ClearCurrentPlayback(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearCurrentPlayback)
	return err
}

const getCurrentPlayback = `-- name: GetCurrentPlayback :one
SELECT id, video_id, started_at, duration_seconds FROM current_playback WHERE id = 1
`

func (q *Queries) GetCurrentPlayback(ctx context.Context) (CurrentPlayback, error) {
	row := q.db.QueryRowContext(ctx, getCurrentPlayback)
	var i CurrentPlayback
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.StartedAt,
		&i.DurationSeconds,
	)
	return i, err
}

const popNextTrack = `-- name: PopNextTrack :one
WITH next_in_queue AS (
    SELECT id, video_id 
    FROM queue 
    ORDER BY position ASC 
    LIMIT 1 
    FOR UPDATE SKIP LOCKED
),
popped_queue AS (
    DELETE FROM queue 
    WHERE id = (SELECT id FROM next_in_queue)
    RETURNING video_id
)
SELECT 
    t.video_id as id,
    t.url, 
    t.duration_seconds, 
    t.track, 
    t.artist, 
    t.album, 
    t.source_media, 
    t.original_composer
FROM popped_queue q
JOIN tracks t ON q.video_id = t.video_id
`

type PopNextTrackRow struct {
	ID               string
	Url              string
	DurationSeconds  sql.NullInt32
	Track            string
	Artist           string
	Album            sql.NullString
	SourceMedia      sql.NullString
	OriginalComposer sql.NullString
}

func (q *Queries) PopNextTrack(ctx context.Context) (PopNextTrackRow, error) {
	row := q.db.QueryRowContext(ctx, popNextTrack)
	var i PopNextTrackRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.DurationSeconds,
		&i.Track,
		&i.Artist,
		&i.Album,
		&i.SourceMedia,
		&i.OriginalComposer,
	)
	return i, err
}

const queueRandomTracks = `-- name: QueueRandomTracks :many
WITH selected_tracks AS (
    SELECT video_id
    FROM tracks
    WHERE ($1::text IS NULL
           OR track ILIKE '%' || REPLACE(REPLACE($1::text, '%', '\%'), '_', '\_') || '%' ESCAPE '\')
      AND ($2::text IS NULL
           OR artist ILIKE '%' || REPLACE(REPLACE($2::text, '%', '\%'), '_', '\_') || '%' ESCAPE '\')
      AND ($3::text IS NULL
           OR album ILIKE '%' || REPLACE(REPLACE($3::text, '%', '\%'), '_', '\_') || '%' ESCAPE '\')
      AND ($4::text IS NULL
           OR source_media ILIKE '%' || REPLACE(REPLACE($4::text, '%', '\%'), '_', '\_') || '%' ESCAPE '\')
      AND ($5::text IS NULL
           OR original_composer ILIKE '%' || REPLACE(REPLACE($5::text, '%', '\%'), '_', '\_') || '%' ESCAPE '\')
    ORDER BY RANDOM()
    LIMIT GREATEST(1, COALESCE($6::integer, 1))
)
INSERT INTO queue (video_id)
SELECT video_id
FROM selected_tracks
RETURNING video_id
`

type QueueRandomTracksParams struct {
	Track            sql.NullString
	Artist           sql.NullString
	Album            sql.NullString
	SourceMedia      sql.NullString
	OriginalComposer sql.NullString
	LimitCount       sql.NullInt32
}

func (q *Queries) QueueRandomTracks(ctx context.Context, arg QueueRandomTracksParams) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, queueRandomTracks,
		arg.Track,
		arg.Artist,
		arg.Album,
		arg.SourceMedia,
		arg.OriginalComposer,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var video_id sql.NullString
		if err := rows.Scan(&video_id); err != nil {
			return nil, err
		}
		items = append(items, video_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shuffleQueue = `-- name: ShuffleQueue :exec
UPDATE queue SET position = random_order.new_pos
FROM (SELECT id, ROW_NUMBER() OVER (ORDER BY RANDOM()) as new_pos FROM queue) random_order
WHERE queue.id = random_order.id
`

func (q *Queries) ShuffleQueue(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, shuffleQueue)
	return err
}

const trackCurrentPlayback = `-- name: TrackCurrentPlayback :exec
INSERT INTO current_playback (id, video_id, started_at, duration_seconds)
VALUES (1, $1, NOW(), $2)
ON CONFLICT (id) DO UPDATE 
SET video_id = EXCLUDED.video_id, started_at = EXCLUDED.started_at, duration_seconds = EXCLUDED.duration_seconds
`

type TrackCurrentPlaybackParams struct {
	VideoID         sql.NullString
	DurationSeconds sql.NullInt32
}

func (q *Queries) TrackCurrentPlayback(ctx context.Context, arg TrackCurrentPlaybackParams) error {
	_, err := q.db.ExecContext(ctx, trackCurrentPlayback, arg.VideoID, arg.DurationSeconds)
	return err
}

const truncateQueue = `-- name: TruncateQueue :exec
TRUNCATE TABLE queue
`

func (q *Queries) TruncateQueue(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateQueue)
	return err
}
