// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

type Auth struct {
	TwitchBotAccountID string
	TwitchClientID     string
	TwitchClientSecret string
	OauthKey           string
	OathRefreshKey     string
}
