// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Auth struct {
	TwitchBotAccountID string
	TwitchOwnerID      string
	TwitchClientID     string
	TwitchClientSecret string
	OauthKey           string
	OauthRefreshKey    string
	OauthExpiresAt     sql.NullTime
}

type CurrentPlayback struct {
	ID              int32
	VideoID         sql.NullString
	StartedAt       sql.NullTime
	DurationSeconds sql.NullInt32
}

type Queue struct {
	ID       int32
	VideoID  sql.NullString
	Position sql.NullInt32
}

type Quote struct {
	ID        int32
	Quote     string
	Who       sql.NullString
	Game      sql.NullString
	QuoteDate sql.NullTime
}

type Track struct {
	VideoID          string
	Url              string
	Track            string
	Artist           string
	Album            sql.NullString
	SourceMedia      sql.NullString
	OriginalComposer sql.NullString
	DurationSeconds  sql.NullInt32
	ContentIDRisk    sql.NullBool
	Enabled          sql.NullBool
}
