// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quote.sql

package database

import (
	"context"
	"database/sql"
)

const addQuote = `-- name: AddQuote :exec
INSERT INTO quotes (quote, who, game) VALUES ($1, $2, $3)
`

type AddQuoteParams struct {
	Quote string
	Who   sql.NullString
	Game  sql.NullString
}

func (q *Queries) AddQuote(ctx context.Context, arg AddQuoteParams) error {
	_, err := q.db.ExecContext(ctx, addQuote, arg.Quote, arg.Who, arg.Game)
	return err
}

const deleteQuote = `-- name: DeleteQuote :exec
DELETE FROM quotes WHERE id = $1
`

func (q *Queries) DeleteQuote(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteQuote, id)
	return err
}

const getMostRecentQuote = `-- name: GetMostRecentQuote :one
SELECT id, quote, who, game, quote_date FROM quotes ORDER BY quote_date DESC LIMIT 1
`

func (q *Queries) GetMostRecentQuote(ctx context.Context) (Quote, error) {
	row := q.db.QueryRowContext(ctx, getMostRecentQuote)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Quote,
		&i.Who,
		&i.Game,
		&i.QuoteDate,
	)
	return i, err
}

const getQuote = `-- name: GetQuote :one
SELECT id, quote, who, game, quote_date FROM quotes WHERE id = $1
`

func (q *Queries) GetQuote(ctx context.Context, id int32) (Quote, error) {
	row := q.db.QueryRowContext(ctx, getQuote, id)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Quote,
		&i.Who,
		&i.Game,
		&i.QuoteDate,
	)
	return i, err
}

const getRandomQuoteByDate = `-- name: GetRandomQuoteByDate :one
SELECT id, quote, who, game, quote_date FROM quotes WHERE quote_date = $1 ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) GetRandomQuoteByDate(ctx context.Context, quoteDate sql.NullTime) (Quote, error) {
	row := q.db.QueryRowContext(ctx, getRandomQuoteByDate, quoteDate)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Quote,
		&i.Who,
		&i.Game,
		&i.QuoteDate,
	)
	return i, err
}

const getRandomQuoteByGame = `-- name: GetRandomQuoteByGame :one
SELECT id, quote, who, game, quote_date FROM quotes WHERE game = $1 ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) GetRandomQuoteByGame(ctx context.Context, game sql.NullString) (Quote, error) {
	row := q.db.QueryRowContext(ctx, getRandomQuoteByGame, game)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Quote,
		&i.Who,
		&i.Game,
		&i.QuoteDate,
	)
	return i, err
}

const getRandomQuoteByWho = `-- name: GetRandomQuoteByWho :one
SELECT id, quote, who, game, quote_date FROM quotes WHERE who = $1 ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) GetRandomQuoteByWho(ctx context.Context, who sql.NullString) (Quote, error) {
	row := q.db.QueryRowContext(ctx, getRandomQuoteByWho, who)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Quote,
		&i.Who,
		&i.Game,
		&i.QuoteDate,
	)
	return i, err
}

const getRandomQuotesByFilters = `-- name: GetRandomQuotesByFilters :many
WITH selected_quotes AS (
    SELECT id, quote, who, game, quote_date
    FROM quotes
    WHERE ($1::text IS NULL
            OR quote ILIKE '%' || REPLACE(REPLACE($1::text, '%', '\%'), '_', '\_') || '%' ESCAPE '\')
        AND ($2::text IS NULL
            OR who ILIKE '%' || REPLACE(REPLACE($2::text, '%', '\%'), '_', '\_') || '%' ESCAPE '\')
        AND ($3::text IS NULL
            OR game ILIKE '%' || REPLACE(REPLACE($3::text, '%', '\%'), '_', '\_') || '%' ESCAPE '\')
        AND (
            ($4::date IS NULL AND $5::date IS NULL)
            OR quote_date BETWEEN COALESCE($4::date, $5::date)
                            AND COALESCE($5::date, $4::date)
            )
    ORDER BY RANDOM()
    LIMIT GREATEST(1, COALESCE($6::integer, 1))
)
SELECT id, quote, who, game, quote_date
FROM selected_quotes
`

type GetRandomQuotesByFiltersParams struct {
	Quote      sql.NullString
	Who        sql.NullString
	Game       sql.NullString
	StartDate  sql.NullTime
	EndDate    sql.NullTime
	LimitCount sql.NullInt32
}

type GetRandomQuotesByFiltersRow struct {
	ID        int32
	Quote     string
	Who       sql.NullString
	Game      sql.NullString
	QuoteDate sql.NullTime
}

func (q *Queries) GetRandomQuotesByFilters(ctx context.Context, arg GetRandomQuotesByFiltersParams) ([]GetRandomQuotesByFiltersRow, error) {
	rows, err := q.db.QueryContext(ctx, getRandomQuotesByFilters,
		arg.Quote,
		arg.Who,
		arg.Game,
		arg.StartDate,
		arg.EndDate,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRandomQuotesByFiltersRow
	for rows.Next() {
		var i GetRandomQuotesByFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Quote,
			&i.Who,
			&i.Game,
			&i.QuoteDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomQuote = `-- name: RandomQuote :one
SELECT id, quote, who, game, quote_date FROM quotes ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) RandomQuote(ctx context.Context) (Quote, error) {
	row := q.db.QueryRowContext(ctx, randomQuote)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.Quote,
		&i.Who,
		&i.Game,
		&i.QuoteDate,
	)
	return i, err
}

const updateQuote = `-- name: UpdateQuote :exec
UPDATE quotes SET quote = $1, who = $2, game = $3 WHERE id = $4
`

type UpdateQuoteParams struct {
	Quote string
	Who   sql.NullString
	Game  sql.NullString
	ID    int32
}

func (q *Queries) UpdateQuote(ctx context.Context, arg UpdateQuoteParams) error {
	_, err := q.db.ExecContext(ctx, updateQuote,
		arg.Quote,
		arg.Who,
		arg.Game,
		arg.ID,
	)
	return err
}
