services:
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    ports:
      - "5432:5432"
      
  chat-overlay:
    ports:
      - "8080:8080"
  
  song-player:
    ports:
      - "8000:8000"